const app=document.getElementById('app');const openEnvelope=document.getElementById('openEnvelope');const curtain=document.getElementById('curtainScreen');const invitation=document.getElementById('invitation');const nav=document.getElementById('bottomNav');const musicBtn=document.getElementById('musicBtn');const shareBtn=document.getElementById('shareBtn');let opened=false,audioCtx,master,notesTimer;
function openFlow(){if(opened)return;opened=true;app.classList.add('opened');setTimeout(()=>{curtain.classList.add('active')},650);setTimeout(()=>{curtain.classList.add('open')},1050);setTimeout(()=>{invitation.scrollIntoView({behavior:'smooth'});nav.classList.add('show')},2450);setTimeout(()=>{curtain.classList.remove('active');curtain.classList.remove('open')},3600)}
openEnvelope.addEventListener('click',openFlow);openEnvelope.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')openFlow()});
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.18});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
function petals(){const box=document.querySelector('.petals');for(let i=0;i<22;i++){const p=document.createElement('i');p.style.left=Math.random()*100+'%';p.style.animationDuration=(7+Math.random()*8)+'s';p.style.animationDelay=(-Math.random()*9)+'s';p.style.setProperty('--drift',(Math.random()*130-65)+'px');p.style.transform=`scale(${.55+Math.random()*1})`;box.appendChild(p)}}petals();
function playTone(freq,start,dur){const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type='sine';osc.frequency.value=freq;gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(.055,start+.08);gain.gain.exponentialRampToValueAtTime(.001,start+dur);osc.connect(gain).connect(master);osc.start(start);osc.stop(start+dur+.05)}
function startMusic(){audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();master=master||audioCtx.createGain();master.gain.value=.7;master.connect(audioCtx.destination);const seq=[523.25,659.25,783.99,659.25,587.33,698.46,880,698.46];let i=0;notesTimer=setInterval(()=>{const now=audioCtx.currentTime;playTone(seq[i%seq.length],now,1.2);playTone(seq[(i+2)%seq.length]/2,now+.05,1.4);i++},900);musicBtn.textContent='♪ Playing'}
function stopMusic(){clearInterval(notesTimer);notesTimer=null;musicBtn.textContent='♫ Music'}musicBtn.addEventListener('click',()=>notesTimer?stopMusic():startMusic());
shareBtn.addEventListener('click',async()=>{const data={title:'Walima Invitation | Rehan & Hamna',text:'You are invited to Rehan & Hamna Walima',url:location.href};if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);shareBtn.textContent='✓ Copied';setTimeout(()=>shareBtn.textContent='↗ Share',1500)}});
function updateTimer(){const target=new Date('2026-12-13T18:00:00+05:00').getTime();let diff=Math.max(0,target-Date.now());const d=Math.floor(diff/86400000);diff%=86400000;const h=Math.floor(diff/3600000);diff%=3600000;const m=Math.floor(diff/60000);diff%=60000;const s=Math.floor(diff/1000);[d,h,m,s].map(v=>String(v).padStart(2,'0')).forEach((v,i)=>document.querySelectorAll('#timer strong')[i].textContent=v)}updateTimer();setInterval(updateTimer,1000);
const canvas=document.getElementById('scratchCanvas'),ctx=canvas.getContext('2d'),scratchCard=document.getElementById('scratchCard');function paintScratch(){const w=canvas.width,h=canvas.height;const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,'#c59a4a');g.addColorStop(.45,'#ead19c');g.addColorStop(1,'#b98738');ctx.globalCompositeOperation='source-over';ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.fillStyle='rgba(255,255,255,.34)';for(let i=0;i<18;i++){ctx.beginPath();ctx.ellipse(Math.random()*w,Math.random()*h,70,9,Math.random()*3.14,0,Math.PI*2);ctx.fill()}ctx.fillStyle='rgba(87,60,46,.72)';ctx.font='600 16px Montserrat';ctx.textAlign='center';ctx.fillText('SCRATCH TO SEE',w/2,h/2+5)}paintScratch();
function pos(e){const r=canvas.getBoundingClientRect();const t=e.touches?e.touches[0]:e;return{x:(t.clientX-r.left)*canvas.width/r.width,y:(t.clientY-r.top)*canvas.height/r.height}}let scratching=false;function scratch(e){if(!scratching)return;e.preventDefault();const p=pos(e);ctx.globalCompositeOperation='destination-out';ctx.beginPath();ctx.arc(p.x,p.y,24,0,Math.PI*2);ctx.fill()}['mousedown','touchstart'].forEach(ev=>canvas.addEventListener(ev,e=>{scratching=true;scratch(e)}));['mousemove','touchmove'].forEach(ev=>canvas.addEventListener(ev,scratch,{passive:false}));['mouseup','mouseleave','touchend'].forEach(ev=>canvas.addEventListener(ev,()=>scratching=false));
